function __global_object_depths() {
	gml_pragma( "global", "__global_object_depths()");

	global.__objectDepths[0] = 98global.__objectDepths[1] = -6global.__objectDepths[2] = -9998global.__objectDepths[3] = 0global.__objectDepths[4] = 0global.__objectDepths[5] = 0global.__objectDepths[6] = 0global.__objectDepths[7] = 0global.__objectDepths[8] = 0global.__objectDepths[9] = 0global.__objectDepths[10] = 0global.__objectDepths[11] = 0global.__objectDepths[12] = 0global.__objectDepths[13] = 0global.__objectDepths[14] = 0global.__objectDepths[15] = 0global.__objectDepths[16] = 0global.__objectDepths[17] = 0global.__objectDepths[18] = 0global.__objectDepths[19] = 2global.__objectDepths[20] = 0global.__objectDepths[21] = -1global.__objectDepths[22] = 0global.__objectDepths[23] = 0global.__objectDepths[24] = 1global.__objectDepths[25] = 0global.__objectDepths[26] = -9999global.__objectDepths[27] = 10global.__objectDepths[28] = 0global.__objectDepths[29] = 0global.__objectDepths[30] = -7global.__objectDepths[31] = 0global.__objectDepths[32] = 0global.__objectDepths[33] = 0global.__objectDepths[34] = 0global.__objectDepths[35] = 0global.__objectDepths[36] = 0global.__objectDepths[37] = 0global.__objectDepths[38] = 0global.__objectDepths[39] = 0global.__objectDepths[40] = 0global.__objectDepths[41] = 0global.__objectDepths[42] = 0global.__objectDepths[43] = 0global.__objectDepths[44] = 0global.__objectDepths[45] = 0global.__objectDepths[46] = 0global.__objectDepths[47] = 0global.__objectDepths[48] = 0global.__objectDepths[49] = 0global.__objectDepths[50] = 0global.__objectDepths[51] = 0global.__objectDepths[52] = 0global.__objectDepths[53] = 0global.__objectDepths[54] = 0global.__objectDepths[55] = 0global.__objectDepths[56] = 0global.__objectDepths[57] = 0global.__objectDepths[58] = 0global.__objectDepths[59] = 0global.__objectDepths[60] = 0global.__objectDepths[61] = 0global.__objectDepths[62] = 0global.__objectDepths[63] = 0global.__objectDepths[64] = 0global.__objectDepths[65] = 0global.__objectDepths[66] = 0global.__objectDepths[67] = 0global.__objectDepths[68] = 0global.__objectDepths[69] = 0global.__objectDepths[70] = 0global.__objectDepths[71] = -2global.__objectDepths[72] = 2global.__objectDepths[73] = 0global.__objectDepths[74] = 999global.__objectDepths[75] = 1global.__objectDepths[76] = 2global.__objectDepths[77] = 1global.__objectDepths[78] = 2global.__objectDepths[79] = 1global.__objectDepths[80] = 1global.__objectDepths[81] = 1global.__objectDepths[82] = 0global.__objectDepths[83] = 0global.__objectDepths[84] = 0global.__objectDepths[85] = 0global.__objectDepths[86] = 2global.__objectDepths[87] = 0global.__objectDepths[88] = 0global.__objectDepths[89] = 0global.__objectDepths[90] = 0global.__objectDepths[91] = 0global.__objectDepths[92] = 2global.__objectDepths[93] = 3global.__objectDepths[94] = 1global.__objectDepths[95] = 0global.__objectDepths[96] = 0global.__objectDepths[97] = 0global.__objectDepths[98] = 0global.__objectDepths[99] = 0global.__objectDepths[100] = 0global.__objectDepths[101] = 1global.__objectDepths[102] = 1global.__objectDepths[103] = 0global.__objectDepths[104] = 1global.__objectDepths[105] = 0global.__objectDepths[106] = 2global.__objectDepths[107] = 0global.__objectDepths[108] = 0global.__objectDepths[109] = -2global.__objectDepths[110] = 0global.__objectDepths[111] = -7global.__objectDepths[112] = 0global.__objectDepths[113] = 0global.__objectDepths[114] = 0global.__objectDepths[115] = 2global.__objectDepths[116] = 0global.__objectDepths[117] = 0global.__objectDepths[118] = 0global.__objectDepths[119] = -1global.__objectDepths[120] = 0global.__objectDepths[121] = -1global.__objectDepths[122] = 0global.__objectDepths[123] = 0global.__objectDepths[124] = 5global.__objectDepths[125] = 0global.__objectDepths[126] = 0global.__objectDepths[127] = 5global.__objectDepths[128] = 1global.__objectDepths[129] = 0global.__objectDepths[130] = 5global.__objectDepths[131] = 5global.__objectDepths[132] = 5global.__objectDepths[133] = 0global.__objectDepths[134] = 10global.__objectDepths[135] = 0global.__objectDepths[136] = 0global.__objectDepths[137] = 0global.__objectDepths[138] = 0global.__objectDepths[139] = 0global.__objectDepths[140] = 0global.__objectDepths[141] = 0global.__objectDepths[142] = 0global.__objectDepths[143] = 0global.__objectDepths[144] = 0global.__objectDepths[145] = 0global.__objectDepths[146] = 0global.__objectDepths[147] = 0global.__objectDepths[148] = 1global.__objectDepths[149] = 0global.__objectDepths[150] = 1global.__objectDepths[151] = 0global.__objectDepths[152] = 0global.__objectDepths[153] = 0global.__objectDepths[154] = -2global.__objectDepths[155] = -2global.__objectDepths[156] = -2global.__objectDepths[157] = -2global.__objectDepths[158] = 0global.__objectDepths[159] = -2global.__objectDepths[160] = -7global.__objectDepths[161] = -7global.__objectDepths[162] = -2global.__objectDepths[163] = 0global.__objectDepths[164] = -4global.__objectDepths[165] = -2global.__objectDepths[166] = 0global.__objectDepths[167] = 0global.__objectDepths[168] = -4global.__objectDepths[169] = 0global.__objectDepths[170] = 0global.__objectDepths[171] = -9999global.__objectDepths[172] = 2global.__objectDepths[173] = 0global.__objectDepths[174] = 0global.__objectDepths[175] = 0global.__objectDepths[176] = -2global.__objectDepths[177] = 0global.__objectDepths[178] = 0global.__objectDepths[179] = 0global.__objectDepths[180] = 0global.__objectDepths[181] = 0global.__objectDepths[182] = 1global.__objectDepths[183] = -9999global.__objectDepths[184] = -9999global.__objectDepths[185] = 2global.__objectDepths[186] = -7global.__objectDepths[187] = -7global.__objectDepths[188] = -7global.__objectDepths[189] = -7global.__objectDepths[190] = -7global.__objectDepths[191] = 2global.__objectDepths[192] = -2global.__objectDepths[193] = 2global.__objectDepths[194] = 2global.__objectDepths[195] = 20global.__objectDepths[196] = 0global.__objectDepths[197] = 99global.__objectDepths[198] = 1global.__objectDepths[199] = 999global.__objectDepths[200] = 0global.__objectDepths[201] = 0global.__objectDepths[202] = 0global.__objectDepths[203] = 0global.__objectDepths[204] = 0global.__objectDepths[205] = -7global.__objectDepths[206] = -7global.__objectDepths[207] = -7global.__objectDepths[208] = 0global.__objectDepths[209] = 0global.__objectDepths[210] = 0global.__objectDepths[211] = 0global.__objectDepths[212] = 0global.__objectDepths[213] = -10global.__objectDepths[214] = -10global.__objectDepths[215] = -2global.__objectDepths[216] = 0global.__objectDepths[217] = 0global.__objectDepths[218] = 0global.__objectDepths[219] = 0global.__objectDepths[220] = 0global.__objectDepths[221] = -10global.__objectDepths[222] = -9999global.__objectDepths[223] = -6global.__objectDepths[224] = -1global.__objectDepths[225] = 0global.__objectDepths[226] = -1global.__objectDepths[227] = 0global.__objectDepths[228] = 0global.__objectDepths[229] = -6global.__objectDepths[230] = -3global.__objectDepths[231] = -6global.__objectDepths[232] = -6global.__objectDepths[233] = -6global.__objectDepths[234] = -6global.__objectDepths[235] = -6global.__objectDepths[236] = -6global.__objectDepths[237] = 0global.__objectDepths[238] = -4

	global.__objectNames[0] = "obj_solid"global.__objectNames[1] = "obj_player"global.__objectNames[2] = "obj_pause"global.__objectNames[3] = "obj_music"global.__objectNames[4] = "obj_tv"global.__objectNames[5] = "obj_basement1timerstart"global.__objectNames[6] = "obj_basement2timerstart"global.__objectNames[7] = "obj_bosshealth"global.__objectNames[8] = "obj_camera"global.__objectNames[9] = "obj_destructibles"global.__objectNames[10] = "obj_solid"global.__objectNames[11] = "obj_solid"global.__objectNames[12] = "obj_solid"global.__objectNames[13] = "obj_saveroom"global.__objectNames[14] = "obj_panicdebris"global.__objectNames[15] = "obj_controller"global.__objectNames[16] = "obj_title"global.__objectNames[17] = "obj_cursor"global.__objectNames[18] = "obj_menuselections"global.__objectNames[19] = "obj_hard"global.__objectNames[20] = "obj_controls"global.__objectNames[21] = "obj_keyconfig"global.__objectNames[22] = "obj_pizzastand"global.__objectNames[23] = "obj_mouthhitbox"global.__objectNames[24] = "obj_hungrypillar"global.__objectNames[25] = "obj_cutscene_upstairs"global.__objectNames[26] = "obj_rank"global.__objectNames[27] = "obj_timesup"global.__objectNames[28] = "obj_rockcutscene"global.__objectNames[29] = "obj_titlecutscene"global.__objectNames[30] = "obj_noise_pushbutton"global.__objectNames[31] = "obj_hookshot"global.__objectNames[32] = "obj_swordhitbox"global.__objectNames[33] = "obj_slaphitbox"global.__objectNames[34] = "obj_shotgunbullet"global.__objectNames[35] = "obj_hurtbox"global.__objectNames[36] = "obj_baddiecollisionbox"global.__objectNames[37] = "obj_boss"global.__objectNames[38] = "obj_baddie"global.__objectNames[39] = "obj_baddiedead"global.__objectNames[40] = "obj_robotknife"global.__objectNames[41] = "obj_spitcheesespike"global.__objectNames[42] = "obj_pineahitbox"global.__objectNames[43] = "obj_sausagemancigar"global.__objectNames[44] = "obj_forkhitbox"global.__objectNames[45] = "obj_sausageman_dead"global.__objectNames[46] = "obj_enemybird"global.__objectNames[47] = "obj_slimedead"global.__objectNames[48] = "obj_pizzaboy"global.__objectNames[49] = "obj_cheeseslime"global.__objectNames[50] = "obj_cheeserobot"global.__objectNames[51] = "obj_robot"global.__objectNames[52] = "obj_pizzagoblin"global.__objectNames[53] = "obj_piraneapple"global.__objectNames[54] = "obj_coolpinea"global.__objectNames[55] = "obj_bigcheese"global.__objectNames[56] = "obj_pizzaball"global.__objectNames[57] = "obj_spitcheese"global.__objectNames[58] = "obj_trash"global.__objectNames[59] = "obj_invtrash"global.__objectNames[60] = "obj_peasanto"global.__objectNames[61] = "obj_ninja"global.__objectNames[62] = "obj_forknight"global.__objectNames[63] = "obj_noisey"global.__objectNames[64] = "obj_flyingenemy"global.__objectNames[65] = "obj_sausageman"global.__objectNames[66] = "obj_crushershockwave"global.__objectNames[67] = "obj_noisecrusher"global.__objectNames[68] = "obj_pepperbombspawner"global.__objectNames[69] = "obj_peppermanbomb"global.__objectNames[70] = "obj_pepperman"global.__objectNames[71] = "obj_peppermancharge"global.__objectNames[72] = "obj_platform"global.__objectNames[73] = "obj_platform"global.__objectNames[74] = "obj_slope"global.__objectNames[75] = "obj_ladder"global.__objectNames[76] = "obj_destroyable"global.__objectNames[77] = "obj_desertdestroyable"global.__objectNames[78] = "obj_destroyable2"global.__objectNames[79] = "obj_destroyable3"global.__objectNames[80] = "obj_metalblock"global.__objectNames[81] = "obj_destroyable2_big"global.__objectNames[82] = "obj_cheeseballblock"global.__objectNames[83] = "obj_bombblock"global.__objectNames[84] = "obj_reverseminipillar"global.__objectNames[85] = "obj_minipillar"global.__objectNames[86] = "obj_spike"global.__objectNames[87] = "obj_null"global.__objectNames[88] = "obj_healthpickup"global.__objectNames[89] = "obj_shotgunpickup"global.__objectNames[90] = "obj_spaghetti"global.__objectNames[91] = "obj_shotgun"global.__objectNames[92] = "obj_pizzaboxunopen"global.__objectNames[93] = "obj_treasure"global.__objectNames[94] = "obj_collect"global.__objectNames[95] = "obj_pizzakinsausage"global.__objectNames[96] = "obj_pizzakinshroom"global.__objectNames[97] = "obj_pizzakincheese"global.__objectNames[98] = "obj_pizzakintomato"global.__objectNames[99] = "obj_pizzakinpineapple"global.__objectNames[100] = "obj_pizzacoin"global.__objectNames[101] = "obj_bigcollect"global.__objectNames[102] = "obj_clockcollectibles"global.__objectNames[103] = "obj_key"global.__objectNames[104] = "obj_clockcollectibles2"global.__objectNames[105] = "obj_phonebooth"global.__objectNames[106] = "obj_exitgate"global.__objectNames[107] = "obj_cheeseball"global.__objectNames[108] = "obj_wetfloor"global.__objectNames[109] = "obj_bomb"global.__objectNames[110] = "obj_noisebombspawner"global.__objectNames[111] = "obj_bombexplosion"global.__objectNames[112] = "obj_slipnslide"global.__objectNames[113] = "obj_superspring"global.__objectNames[114] = "obj_beartrap"global.__objectNames[115] = "obj_balloon"global.__objectNames[116] = "obj_dashpad"global.__objectNames[117] = "obj_bowlingball"global.__objectNames[118] = "obj_skateboard"global.__objectNames[119] = "obj_pizzacutterthwomp2"global.__objectNames[120] = "obj_pizzacutterthwomp1"global.__objectNames[121] = "obj_pizzacutter2"global.__objectNames[122] = "obj_pizzacutter1"global.__objectNames[123] = "obj_breakabledoor"global.__objectNames[124] = "obj_keydoor"global.__objectNames[125] = "obj_portalend"global.__objectNames[126] = "obj_portalentrance"global.__objectNames[127] = "obj_goldendoor"global.__objectNames[128] = "obj_doorblocked"global.__objectNames[129] = "obj_startgate"global.__objectNames[130] = "obj_door"global.__objectNames[131] = "obj_hallway"global.__objectNames[132] = "obj_door2"global.__objectNames[133] = "obj_grindrail"global.__objectNames[134] = "obj_swordstone"global.__objectNames[135] = "obj_thunder"global.__objectNames[136] = "obj_grabbiehand"global.__objectNames[137] = "obj_boxcrusher"global.__objectNames[138] = "obj_cheeseblob"global.__objectNames[139] = "obj_cheesemaker"global.__objectNames[140] = "obj_railv"global.__objectNames[141] = "obj_railh2"global.__objectNames[142] = "obj_railh"global.__objectNames[143] = "obj_hook"global.__objectNames[144] = "obj_hookup"global.__objectNames[145] = "obj_hookleft"global.__objectNames[146] = "obj_barrelspawner"global.__objectNames[147] = "obj_transformbarrelspawner"global.__objectNames[148] = "obj_transformbarrel"global.__objectNames[149] = "obj_barrel"global.__objectNames[150] = "obj_barrelfloat"global.__objectNames[151] = "obj_tomatoblock"global.__objectNames[152] = "obj_destructibleplatform"global.__objectNames[153] = "obj_baddiegibs"global.__objectNames[154] = "obj_wooddebris"global.__objectNames[155] = "obj_slapstar"global.__objectNames[156] = "obj_pizzadebris"global.__objectNames[157] = "obj_debris"global.__objectNames[158] = "obj_dripspawner"global.__objectNames[159] = "object189"global.__objectNames[160] = "obj_knightdebris"global.__objectNames[161] = "obj_boxxeddebris"global.__objectNames[162] = "obj_glassdebris"global.__objectNames[163] = "obj_vomit"global.__objectNames[164] = "obj_slimedebris"global.__objectNames[165] = "obj_metaldebris"global.__objectNames[166] = "obj_drip"global.__objectNames[167] = "obj_skateboarddebris1"global.__objectNames[168] = "obj_lock"global.__objectNames[169] = "obj_pizzaloss"global.__objectNames[170] = "obj_skateboarddebris2"global.__objectNames[171] = "obj_vsscreen"global.__objectNames[172] = "obj_goalsign"global.__objectNames[173] = "obj_siren"global.__objectNames[174] = "obj_exitdoorsign"global.__objectNames[175] = "obj_plusseconds"global.__objectNames[176] = "obj_ranksign"global.__objectNames[177] = "obj_donesign"global.__objectNames[178] = "obj_Hranksign"global.__objectNames[179] = "obj_press"global.__objectNames[180] = "obj_uparrow"global.__objectNames[181] = "obj_creditimages"global.__objectNames[182] = "obj_leveltitles"global.__objectNames[183] = "obj_retry"global.__objectNames[184] = "obj_exit"global.__objectNames[185] = "obj_easy"global.__objectNames[186] = "obj_100"global.__objectNames[187] = "obj_80"global.__objectNames[188] = "obj_40"global.__objectNames[189] = "obj_20"global.__objectNames[190] = "obj_10"global.__objectNames[191] = "obj_ballgoal"global.__objectNames[192] = "obj_noisesatellite"global.__objectNames[193] = "obj_glassblock"global.__objectNames[194] = "obj_tutorialtrap"global.__objectNames[195] = "obj_crashingplane"global.__objectNames[196] = "obj_crashplaneblock"global.__objectNames[197] = "obj_parrallax"global.__objectNames[198] = "obj_lamp"global.__objectNames[199] = "obj_lightlamp"global.__objectNames[200] = "obj_speedlines"global.__objectNames[201] = "obj_pizzaportalfade"global.__objectNames[202] = "obj_angrycloud"global.__objectNames[203] = "obj_sweat"global.__objectNames[204] = "obj_balloonpop"global.__objectNames[205] = "obj_bulletimpact"global.__objectNames[206] = "obj_bulletdisappear"global.__objectNames[207] = "obj_chargeeffect"global.__objectNames[208] = "obj_pogoeffect"global.__objectNames[209] = "obj_chainsaweffect"global.__objectNames[210] = "obj_explosioneffect"global.__objectNames[211] = "obj_pistoleffect"global.__objectNames[212] = "obj_shotgunjumpeffect"global.__objectNames[213] = "obj_superslameffect"global.__objectNames[214] = "obj_spikehurteffect"global.__objectNames[215] = "obj_stompeffect"global.__objectNames[216] = "obj_jumpdust"global.__objectNames[217] = "obj_superdashcloud"global.__objectNames[218] = "obj_highjumpcloud1"global.__objectNames[219] = "obj_highjumpcloud2"global.__objectNames[220] = "obj_grindeffect"global.__objectNames[221] = "obj_punchdust"global.__objectNames[222] = "obj_fadeout"global.__objectNames[223] = "obj_endlevelfade"global.__objectNames[224] = "obj_bossdefeatflash"global.__objectNames[225] = "obj_bangeffect"global.__objectNames[226] = "obj_blackbars"global.__objectNames[227] = "obj_bumpeffect"global.__objectNames[228] = "obj_keyeffect"global.__objectNames[229] = "obj_doortransition"global.__objectNames[230] = "obj_doortransitionend"global.__objectNames[231] = "obj_doortransition2"global.__objectNames[232] = "obj_slidecloud"global.__objectNames[233] = "obj_landcloud"global.__objectNames[234] = "obj_dashcloud"global.__objectNames[235] = "obj_dashcloud2"global.__objectNames[236] = "obj_cloudeffect"global.__objectNames[237] = "obj_machalleffect"global.__objectNames[238] = "obj_mach3effect"

	global.__objectDepths[239] = 0; // obj_slope
	global.__objectDepths[240] = 0; // obj_solid
	global.__objectDepths[241] = 0; // obj_player
	global.__objectDepths[242] = 0; // obj_player1
	global.__objectDepths[243] = 0; // obj_player2
	global.__objectDepths[244] = 0; // obj_pause
	global.__objectDepths[245] = 0; // obj_music
	global.__objectDepths[246] = 0; // obj_tv
	global.__objectDepths[247] = 0; // obj_bosshealth
	global.__objectDepths[248] = 0; // obj_camera
	global.__objectDepths[249] = 0; // obj_camera2
	global.__objectDepths[250] = 0; // obj_destructibles
	global.__objectDepths[251] = 0; // obj_bigdestructibles
	global.__objectDepths[252] = 0; // obj_saveroom
	global.__objectDepths[253] = 0; // obj_panicdebris
	global.__objectDepths[254] = 0; // obj_controller
	global.__objectDepths[255] = 0; // obj_stylebar
	global.__objectDepths[256] = 0; // obj_parrallax
	global.__objectDepths[257] = 0; // obj_pizzacoinindicator
	global.__objectDepths[258] = 0; // obj_secretfound
	global.__objectDepths[259] = 0; // obj_title
	global.__objectDepths[260] = 0; // obj_mainmenuselect
	global.__objectDepths[261] = 0; // obj_option
	global.__objectDepths[262] = 0; // obj_erasegame
	global.__objectDepths[263] = 0; // obj_keyconfig
	global.__objectDepths[264] = 0; // obj_cursor
	global.__objectDepths[265] = 0; // obj_menuselections
	global.__objectDepths[266] = 0; // obj_hard
	global.__objectDepths[267] = 0; // obj_controls
	global.__objectDepths[268] = 0; // obj_file1
	global.__objectDepths[269] = 0; // obj_file3
	global.__objectDepths[270] = 0; // obj_file2
	global.__objectDepths[271] = 0; // obj_retry
	global.__objectDepths[272] = 0; // obj_exit
	global.__objectDepths[273] = 0; // obj_manual
	global.__objectDepths[274] = 0; // obj_pizzastand
	global.__objectDepths[275] = 0; // obj_mouthhitbox
	global.__objectDepths[276] = 0; // obj_cutscene_upstairs
	global.__objectDepths[277] = 0; // obj_rank
	global.__objectDepths[278] = 0; // obj_timesup
	global.__objectDepths[279] = 0; // obj_rockcutscene
	global.__objectDepths[280] = 0; // obj_titlecutscene
	global.__objectDepths[281] = 0; // obj_noise_pushbutton
	global.__objectDepths[282] = 0; // obj_ufotransition
	global.__objectDepths[283] = 0; // obj_bomb
	global.__objectDepths[284] = 0; // obj_bombexplosion
	global.__objectDepths[285] = 0; // obj_hookshot
	global.__objectDepths[286] = 0; // obj_swordhitbox
	global.__objectDepths[287] = 0; // obj_slaphitbox
	global.__objectDepths[288] = 0; // obj_slaphitbox2
	global.__objectDepths[289] = 0; // obj_shotgunbullet
	global.__objectDepths[290] = 0; // obj_hurtbox
	global.__objectDepths[291] = 0; // obj_pistolbullet
	global.__objectDepths[292] = 0; // obj_firemouth_projectile
	global.__objectDepths[293] = 0; // obj_swingdinghitbox
	global.__objectDepths[294] = 0; // obj_baddiecollisionbox
	global.__objectDepths[295] = 0; // obj_boss
	global.__objectDepths[296] = 0; // obj_baddie
	global.__objectDepths[297] = 0; // obj_baddiedead
	global.__objectDepths[298] = 0; // obj_pizzagoblinbomb
	global.__objectDepths[299] = 0; // obj_robotknife
	global.__objectDepths[300] = 0; // obj_spitcheesespike
	global.__objectDepths[301] = 0; // obj_pineahitbox
	global.__objectDepths[302] = 0; // obj_sausagemancigar
	global.__objectDepths[303] = 0; // obj_forkhitbox
	global.__objectDepths[304] = 0; // obj_pepgoblin_kickhitbox
	global.__objectDepths[305] = 0; // obj_kentukykenny_projectile
	global.__objectDepths[306] = 0; // obj_pizzard_bolt
	global.__objectDepths[307] = 0; // obj_sausageman_dead
	global.__objectDepths[308] = 0; // obj_enemybird
	global.__objectDepths[309] = 0; // obj_slimedead
	global.__objectDepths[310] = 0; // obj_enemybandaid
	global.__objectDepths[311] = 0; // obj_cheeseslime
	global.__objectDepths[312] = 0; // obj_pizzaboy
	global.__objectDepths[313] = 0; // obj_pizzice
	global.__objectDepths[314] = 0; // obj_cheeserobot
	global.__objectDepths[315] = 0; // obj_robot
	global.__objectDepths[316] = 0; // obj_kentukykenny
	global.__objectDepths[317] = 0; // obj_pizzagoblin
	global.__objectDepths[318] = 0; // obj_pizzard
	global.__objectDepths[319] = 0; // obj_pepgoblin
	global.__objectDepths[320] = 0; // obj_piraneapple
	global.__objectDepths[321] = 0; // obj_coolpinea
	global.__objectDepths[322] = 0; // obj_bigcheese
	global.__objectDepths[323] = 0; // obj_pizzaball
	global.__objectDepths[324] = 0; // obj_spitcheese
	global.__objectDepths[325] = 0; // obj_trash
	global.__objectDepths[326] = 0; // obj_invtrash
	global.__objectDepths[327] = 0; // obj_peasanto
	global.__objectDepths[328] = 0; // obj_ninja
	global.__objectDepths[329] = 0; // obj_forknight
	global.__objectDepths[330] = 0; // obj_ancho
	global.__objectDepths[331] = 0; // obj_indiancheese
	global.__objectDepths[332] = 0; // obj_fencer
	global.__objectDepths[333] = 0; // obj_noisey
	global.__objectDepths[334] = 0; // obj_sausageman
	global.__objectDepths[335] = 0; // obj_grandpa
	global.__objectDepths[336] = 0; // obj_baddiespawner
	global.__objectDepths[337] = 0; // obj_pepperman
	global.__objectDepths[338] = 0; // obj_peppermandestroyable
	global.__objectDepths[339] = 0; // obj_peppermancharge
	global.__objectDepths[340] = 0; // obj_fakepeppino
	global.__objectDepths[341] = 0; // obj_crushershockwave
	global.__objectDepths[342] = 0; // obj_noisecrusher
	global.__objectDepths[343] = 0; // obj_pepperbombspawner
	global.__objectDepths[344] = 0; // obj_peppermanbomb
	global.__objectDepths[345] = 0; // obj_ladder
	global.__objectDepths[346] = 0; // obj_platform
	global.__objectDepths[347] = 0; // obj_destroyable
	global.__objectDepths[348] = 0; // obj_destroyableescape
	global.__objectDepths[349] = 0; // obj_secretblock
	global.__objectDepths[350] = 0; // obj_desertdestroyable
	global.__objectDepths[351] = 0; // obj_destroyable2
	global.__objectDepths[352] = 0; // obj_destroyable2escape
	global.__objectDepths[353] = 0; // obj_destroyable3
	global.__objectDepths[354] = 0; // obj_destroyable3escape
	global.__objectDepths[355] = 0; // obj_secretbigblock
	global.__objectDepths[356] = 0; // obj_metalblock
	global.__objectDepths[357] = 0; // obj_metalblockescape
	global.__objectDepths[358] = 0; // obj_secretmetalblock
	global.__objectDepths[359] = 0; // obj_destroyable2_big
	global.__objectDepths[360] = 0; // obj_destroyable2_bigescape
	global.__objectDepths[361] = 0; // obj_cheeseballblock
	global.__objectDepths[362] = 0; // obj_bombblock
	global.__objectDepths[363] = 0; // obj_reverseminipillar
	global.__objectDepths[364] = 0; // obj_minipillar
	global.__objectDepths[365] = 0; // obj_spike
	global.__objectDepths[366] = 0; // obj_movingoutlet
	global.__objectDepths[367] = 0; // obj_null
	global.__objectDepths[368] = 0; // obj_unclimbablewall
	global.__objectDepths[369] = 0; // obj_grindrail
	global.__objectDepths[370] = 0; // obj_targetblock
	global.__objectDepths[371] = 0; // obj_weaponmachine
	global.__objectDepths[372] = 0; // obj_shotgun
	global.__objectDepths[373] = 0; // obj_breakabletv
	global.__objectDepths[374] = 0; // obj_treasure
	global.__objectDepths[375] = 0; // obj_pizzaboxunopen
	global.__objectDepths[376] = 0; // obj_collect
	global.__objectDepths[377] = 0; // obj_pizzakinsausage
	global.__objectDepths[378] = 0; // obj_pizzakinshroom
	global.__objectDepths[379] = 0; // obj_pizzakincheese
	global.__objectDepths[380] = 0; // obj_pizzakintomato
	global.__objectDepths[381] = 0; // obj_pizzakinpineapple
	global.__objectDepths[382] = 0; // obj_noisebomb
	global.__objectDepths[383] = 0; // obj_bigcollect
	global.__objectDepths[384] = 0; // obj_giantcollect
	global.__objectDepths[385] = 0; // obj_clockcollectibles
	global.__objectDepths[386] = 0; // obj_key
	global.__objectDepths[387] = 0; // obj_clockcollectibles2
	global.__objectDepths[388] = 0; // obj_pizzaslice
	global.__objectDepths[389] = 0; // obj_pizzacoin
	global.__objectDepths[390] = 0; // obj_phonebooth
	global.__objectDepths[391] = 0; // obj_hungrypillar
	global.__objectDepths[392] = 0; // obj_exitgate
	global.__objectDepths[393] = 0; // obj_snicklevelend
	global.__objectDepths[394] = 0; // obj_portalentrance
	global.__objectDepths[395] = 0; // obj_portalend
	global.__objectDepths[396] = 0; // obj_costumerdoor
	global.__objectDepths[397] = 0; // obj_costumer
	global.__objectDepths[398] = 0; // obj_costumerpizza
	global.__objectDepths[399] = 0; // obj_cheeseball
	global.__objectDepths[400] = 0; // obj_wetfloor
	global.__objectDepths[401] = 0; // obj_noisebombspawner
	global.__objectDepths[402] = 0; // obj_slipnslide
	global.__objectDepths[403] = 0; // obj_superspring
	global.__objectDepths[404] = 0; // obj_sidesuperspring
	global.__objectDepths[405] = 0; // obj_beartrap
	global.__objectDepths[406] = 0; // obj_balloon
	global.__objectDepths[407] = 0; // obj_bowlingball
	global.__objectDepths[408] = 0; // obj_skateboard
	global.__objectDepths[409] = 0; // obj_pizzacutterthwomp2
	global.__objectDepths[410] = 0; // obj_pizzacutterthwomp1
	global.__objectDepths[411] = 0; // obj_throwableparent
	global.__objectDepths[412] = 0; // obj_keydoor
	global.__objectDepths[413] = 0; // obj_breakabledoor
	global.__objectDepths[414] = 0; // obj_goldendoor
	global.__objectDepths[415] = 0; // obj_doorblocked
	global.__objectDepths[416] = 0; // obj_startgate
	global.__objectDepths[417] = 0; // obj_door
	global.__objectDepths[418] = 0; // obj_boxofpizza
	global.__objectDepths[419] = 0; // obj_hallway
	global.__objectDepths[420] = 0; // obj_pitfall
	global.__objectDepths[421] = 0; // obj_door2
	global.__objectDepths[422] = 0; // obj_doorA
	global.__objectDepths[423] = 0; // obj_doorB
	global.__objectDepths[424] = 0; // obj_doorC
	global.__objectDepths[425] = 0; // obj_doorD
	global.__objectDepths[426] = 0; // obj_doorE
	global.__objectDepths[427] = 0; // obj_pizzacutter1
	global.__objectDepths[428] = 0; // obj_swordstone
	global.__objectDepths[429] = 0; // obj_pizzacutter2
	global.__objectDepths[430] = 0; // obj_thunder
	global.__objectDepths[431] = 0; // obj_destructibleplatform
	global.__objectDepths[432] = 0; // obj_boilingsauce
	global.__objectDepths[433] = 0; // obj_risingboilingsauce
	global.__objectDepths[434] = 0; // obj_noisetrap_rock
	global.__objectDepths[435] = 0; // obj_dashpad
	global.__objectDepths[436] = 0; // obj_tntblock
	global.__objectDepths[437] = 0; // obj_rockblock
	global.__objectDepths[438] = 0; // obj_noiserock
	global.__objectDepths[439] = 0; // obj_boulder
	global.__objectDepths[440] = 0; // obj_noisedynamite
	global.__objectDepths[441] = 0; // obj_freemilk
	global.__objectDepths[442] = 0; // obj_motocycle
	global.__objectDepths[443] = 0; // obj_haystack
	global.__objectDepths[444] = 0; // obj_noisehotair
	global.__objectDepths[445] = 0; // obj_noisematch
	global.__objectDepths[446] = 0; // obj_grabbiehand
	global.__objectDepths[447] = 0; // obj_boxcrusher
	global.__objectDepths[448] = 0; // obj_cheeseblob
	global.__objectDepths[449] = 0; // obj_cheesemaker
	global.__objectDepths[450] = 0; // obj_railv
	global.__objectDepths[451] = 0; // obj_railh2
	global.__objectDepths[452] = 0; // obj_railh
	global.__objectDepths[453] = 0; // obj_hook
	global.__objectDepths[454] = 0; // obj_hookup
	global.__objectDepths[455] = 0; // obj_hookleft
	global.__objectDepths[456] = 0; // obj_barrelspawner
	global.__objectDepths[457] = 0; // obj_transformbarrelspawner
	global.__objectDepths[458] = 0; // obj_transformbarrel
	global.__objectDepths[459] = 0; // obj_barrel
	global.__objectDepths[460] = 0; // obj_barrelfloat
	global.__objectDepths[461] = 0; // obj_tomatoblock
	global.__objectDepths[462] = 0; // obj_washingmachinemount
	global.__objectDepths[463] = 0; // obj_baddiegibs
	global.__objectDepths[464] = 0; // obj_washingmachine
	global.__objectDepths[465] = 0; // obj_wooddebris
	global.__objectDepths[466] = 0; // obj_slapstar
	global.__objectDepths[467] = 0; // obj_pizzadebris
	global.__objectDepths[468] = 0; // obj_debris
	global.__objectDepths[469] = 0; // obj_dripspawner
	global.__objectDepths[470] = 0; // object189
	global.__objectDepths[471] = 0; // obj_knightdebris
	global.__objectDepths[472] = 0; // obj_boxxeddebris
	global.__objectDepths[473] = 0; // obj_glassdebris
	global.__objectDepths[474] = 0; // obj_vomit
	global.__objectDepths[475] = 0; // obj_slimedebris
	global.__objectDepths[476] = 0; // obj_metaldebris
	global.__objectDepths[477] = 0; // obj_drip
	global.__objectDepths[478] = 0; // obj_skateboarddebris1
	global.__objectDepths[479] = 0; // obj_lock
	global.__objectDepths[480] = 0; // obj_pizzaloss
	global.__objectDepths[481] = 0; // obj_skateboarddebris2
	global.__objectDepths[482] = 0; // obj_parentparticle
	global.__objectDepths[483] = 0; // obj_tntblockdebris
	global.__objectDepths[484] = 0; // obj_vsscreen
	global.__objectDepths[485] = 0; // obj_goalsign
	global.__objectDepths[486] = 0; // obj_siren
	global.__objectDepths[487] = 0; // obj_exitdoorsign
	global.__objectDepths[488] = 0; // obj_plusseconds
	global.__objectDepths[489] = 0; // obj_ranksign
	global.__objectDepths[490] = 0; // obj_donesign
	global.__objectDepths[491] = 0; // obj_Hranksign
	global.__objectDepths[492] = 0; // obj_press
	global.__objectDepths[493] = 0; // obj_uparrow
	global.__objectDepths[494] = 0; // obj_creditimages
	global.__objectDepths[495] = 0; // obj_leveltitles
	global.__objectDepths[496] = 0; // obj_easy
	global.__objectDepths[497] = 0; // obj_100
	global.__objectDepths[498] = 0; // obj_80
	global.__objectDepths[499] = 0; // obj_40
	global.__objectDepths[500] = 0; // obj_20
	global.__objectDepths[501] = 0; // obj_smallnumber
	global.__objectDepths[502] = 0; // obj_cowboyhat
	global.__objectDepths[503] = 0; // obj_treasureshadow
	global.__objectDepths[504] = 0; // obj_Opeppino
	global.__objectDepths[505] = 0; // obj_itspizzatime
	global.__objectDepths[506] = 0; // obj_grabmarker
	global.__objectDepths[507] = 0; // obj_ballgoal
	global.__objectDepths[508] = 0; // obj_noisesatellite
	global.__objectDepths[509] = 0; // obj_glassblock
	global.__objectDepths[510] = 0; // obj_tutorialtrap
	global.__objectDepths[511] = 0; // obj_crashingplane
	global.__objectDepths[512] = 0; // obj_crashplaneblock
	global.__objectDepths[513] = 0; // obj_pizzaballblock
	global.__objectDepths[514] = 0; // obj_lamp
	global.__objectDepths[515] = 0; // obj_lightlamp
	global.__objectDepths[516] = 0; // obj_daynight
	global.__objectDepths[517] = 0; // obj_speedlines
	global.__objectDepths[518] = 0; // obj_pizzaportalfade
	global.__objectDepths[519] = 0; // obj_angrycloud
	global.__objectDepths[520] = 0; // obj_sweat
	global.__objectDepths[521] = 0; // obj_balloonpop
	global.__objectDepths[522] = 0; // obj_bulletimpact
	global.__objectDepths[523] = 0; // obj_bulletdisappear
	global.__objectDepths[524] = 0; // obj_chargeeffect
	global.__objectDepths[525] = 0; // obj_pogoeffect
	global.__objectDepths[526] = 0; // obj_chainsaweffect
	global.__objectDepths[527] = 0; // obj_explosioneffect
	global.__objectDepths[528] = 0; // obj_pistoleffect
	global.__objectDepths[529] = 0; // obj_shotgunjumpeffect
	global.__objectDepths[530] = 0; // obj_superslameffect
	global.__objectDepths[531] = 0; // obj_spikehurteffect
	global.__objectDepths[532] = 0; // obj_stompeffect
	global.__objectDepths[533] = 0; // obj_jumpdust
	global.__objectDepths[534] = 0; // obj_superdashcloud
	global.__objectDepths[535] = 0; // obj_highjumpcloud1
	global.__objectDepths[536] = 0; // obj_highjumpcloud2
	global.__objectDepths[537] = 0; // obj_grindeffect
	global.__objectDepths[538] = 0; // obj_punchdust
	global.__objectDepths[539] = 0; // obj_fadeout
	global.__objectDepths[540] = 0; // obj_pausefadeout
	global.__objectDepths[541] = 0; // obj_endlevelfade
	global.__objectDepths[542] = 0; // obj_bossdefeatflash
	global.__objectDepths[543] = 0; // obj_bangeffect
	global.__objectDepths[544] = 0; // obj_blackbars
	global.__objectDepths[545] = 0; // obj_bumpeffect
	global.__objectDepths[546] = 0; // obj_keyeffect
	global.__objectDepths[547] = 0; // obj_doortransition
	global.__objectDepths[548] = 0; // obj_doortransitionend
	global.__objectDepths[549] = 0; // obj_doortransition2
	global.__objectDepths[550] = 0; // obj_slidecloud
	global.__objectDepths[551] = 0; // obj_landcloud
	global.__objectDepths[552] = 0; // obj_dashcloud
	global.__objectDepths[553] = 0; // obj_dashcloud2
	global.__objectDepths[554] = 0; // obj_cloudeffect
	global.__objectDepths[555] = 0; // obj_machalleffect
	global.__objectDepths[556] = 0; // obj_mach3effect
	global.__objectDepths[557] = 0; // obj_crazyruneffect
	global.__objectDepths[558] = 0; // obj_crazyrunothereffect
	global.__objectDepths[559] = 0; // obj_taunteffect
	global.__objectDepths[560] = 0; // obj_tauntafterimage
	global.__objectDepths[561] = 0; // obj_tauntaftereffectspawner
	global.__objectDepths[562] = 0; // obj_snick
	global.__objectDepths[563] = 0; // obj_snickexe
	global.__objectDepths[564] = 0; // obj_SAGE2019achievementmarker
	global.__objectDepths[565] = 0; // obj_snickchallengedoor
	global.__objectDepths[566] = 0; // obj_cowboytask
	global.__objectDepths[567] = 0; // obj_cowboyhatpickup
	global.__objectDepths[568] = 0; // obj_characterchangecube


	global.__objectNames[239] = "obj_slope";
	global.__objectNames[240] = "obj_solid";
	global.__objectNames[241] = "obj_player";
	global.__objectNames[242] = "obj_player1";
	global.__objectNames[243] = "obj_player2";
	global.__objectNames[244] = "obj_pause";
	global.__objectNames[245] = "obj_music";
	global.__objectNames[246] = "obj_tv";
	global.__objectNames[247] = "obj_bosshealth";
	global.__objectNames[248] = "obj_camera";
	global.__objectNames[249] = "obj_camera2";
	global.__objectNames[250] = "obj_destructibles";
	global.__objectNames[251] = "obj_bigdestructibles";
	global.__objectNames[252] = "obj_saveroom";
	global.__objectNames[253] = "obj_panicdebris";
	global.__objectNames[254] = "obj_controller";
	global.__objectNames[255] = "obj_stylebar";
	global.__objectNames[256] = "obj_parrallax";
	global.__objectNames[257] = "obj_pizzacoinindicator";
	global.__objectNames[258] = "obj_secretfound";
	global.__objectNames[259] = "obj_title";
	global.__objectNames[260] = "obj_mainmenuselect";
	global.__objectNames[261] = "obj_option";
	global.__objectNames[262] = "obj_erasegame";
	global.__objectNames[263] = "obj_keyconfig";
	global.__objectNames[264] = "obj_cursor";
	global.__objectNames[265] = "obj_menuselections";
	global.__objectNames[266] = "obj_hard";
	global.__objectNames[267] = "obj_controls";
	global.__objectNames[268] = "obj_file1";
	global.__objectNames[269] = "obj_file3";
	global.__objectNames[270] = "obj_file2";
	global.__objectNames[271] = "obj_retry";
	global.__objectNames[272] = "obj_exit";
	global.__objectNames[273] = "obj_manual";
	global.__objectNames[274] = "obj_pizzastand";
	global.__objectNames[275] = "obj_mouthhitbox";
	global.__objectNames[276] = "obj_cutscene_upstairs";
	global.__objectNames[277] = "obj_rank";
	global.__objectNames[278] = "obj_timesup";
	global.__objectNames[279] = "obj_rockcutscene";
	global.__objectNames[280] = "obj_titlecutscene";
	global.__objectNames[281] = "obj_noise_pushbutton";
	global.__objectNames[282] = "obj_ufotransition";
	global.__objectNames[283] = "obj_bomb";
	global.__objectNames[284] = "obj_bombexplosion";
	global.__objectNames[285] = "obj_hookshot";
	global.__objectNames[286] = "obj_swordhitbox";
	global.__objectNames[287] = "obj_slaphitbox";
	global.__objectNames[288] = "obj_slaphitbox2";
	global.__objectNames[289] = "obj_shotgunbullet";
	global.__objectNames[290] = "obj_hurtbox";
	global.__objectNames[291] = "obj_pistolbullet";
	global.__objectNames[292] = "obj_firemouth_projectile";
	global.__objectNames[293] = "obj_swingdinghitbox";
	global.__objectNames[294] = "obj_baddiecollisionbox";
	global.__objectNames[295] = "obj_boss";
	global.__objectNames[296] = "obj_baddie";
	global.__objectNames[297] = "obj_baddiedead";
	global.__objectNames[298] = "obj_pizzagoblinbomb";
	global.__objectNames[299] = "obj_robotknife";
	global.__objectNames[300] = "obj_spitcheesespike";
	global.__objectNames[301] = "obj_pineahitbox";
	global.__objectNames[302] = "obj_sausagemancigar";
	global.__objectNames[303] = "obj_forkhitbox";
	global.__objectNames[304] = "obj_pepgoblin_kickhitbox";
	global.__objectNames[305] = "obj_kentukykenny_projectile";
	global.__objectNames[306] = "obj_pizzard_bolt";
	global.__objectNames[307] = "obj_sausageman_dead";
	global.__objectNames[308] = "obj_enemybird";
	global.__objectNames[309] = "obj_slimedead";
	global.__objectNames[310] = "obj_enemybandaid";
	global.__objectNames[311] = "obj_cheeseslime";
	global.__objectNames[312] = "obj_pizzaboy";
	global.__objectNames[313] = "obj_pizzice";
	global.__objectNames[314] = "obj_cheeserobot";
	global.__objectNames[315] = "obj_robot";
	global.__objectNames[316] = "obj_kentukykenny";
	global.__objectNames[317] = "obj_pizzagoblin";
	global.__objectNames[318] = "obj_pizzard";
	global.__objectNames[319] = "obj_pepgoblin";
	global.__objectNames[320] = "obj_piraneapple";
	global.__objectNames[321] = "obj_coolpinea";
	global.__objectNames[322] = "obj_bigcheese";
	global.__objectNames[323] = "obj_pizzaball";
	global.__objectNames[324] = "obj_spitcheese";
	global.__objectNames[325] = "obj_trash";
	global.__objectNames[326] = "obj_invtrash";
	global.__objectNames[327] = "obj_peasanto";
	global.__objectNames[328] = "obj_ninja";
	global.__objectNames[329] = "obj_forknight";
	global.__objectNames[330] = "obj_ancho";
	global.__objectNames[331] = "obj_indiancheese";
	global.__objectNames[332] = "obj_fencer";
	global.__objectNames[333] = "obj_noisey";
	global.__objectNames[334] = "obj_sausageman";
	global.__objectNames[335] = "obj_grandpa";
	global.__objectNames[336] = "obj_baddiespawner";
	global.__objectNames[337] = "obj_pepperman";
	global.__objectNames[338] = "obj_peppermandestroyable";
	global.__objectNames[339] = "obj_peppermancharge";
	global.__objectNames[340] = "obj_fakepeppino";
	global.__objectNames[341] = "obj_crushershockwave";
	global.__objectNames[342] = "obj_noisecrusher";
	global.__objectNames[343] = "obj_pepperbombspawner";
	global.__objectNames[344] = "obj_peppermanbomb";
	global.__objectNames[345] = "obj_ladder";
	global.__objectNames[346] = "obj_platform";
	global.__objectNames[347] = "obj_destroyable";
	global.__objectNames[348] = "obj_destroyableescape";
	global.__objectNames[349] = "obj_secretblock";
	global.__objectNames[350] = "obj_desertdestroyable";
	global.__objectNames[351] = "obj_destroyable2";
	global.__objectNames[352] = "obj_destroyable2escape";
	global.__objectNames[353] = "obj_destroyable3";
	global.__objectNames[354] = "obj_destroyable3escape";
	global.__objectNames[355] = "obj_secretbigblock";
	global.__objectNames[356] = "obj_metalblock";
	global.__objectNames[357] = "obj_metalblockescape";
	global.__objectNames[358] = "obj_secretmetalblock";
	global.__objectNames[359] = "obj_destroyable2_big";
	global.__objectNames[360] = "obj_destroyable2_bigescape";
	global.__objectNames[361] = "obj_cheeseballblock";
	global.__objectNames[362] = "obj_bombblock";
	global.__objectNames[363] = "obj_reverseminipillar";
	global.__objectNames[364] = "obj_minipillar";
	global.__objectNames[365] = "obj_spike";
	global.__objectNames[366] = "obj_movingoutlet";
	global.__objectNames[367] = "obj_null";
	global.__objectNames[368] = "obj_unclimbablewall";
	global.__objectNames[369] = "obj_grindrail";
	global.__objectNames[370] = "obj_targetblock";
	global.__objectNames[371] = "obj_weaponmachine";
	global.__objectNames[372] = "obj_shotgun";
	global.__objectNames[373] = "obj_breakabletv";
	global.__objectNames[374] = "obj_treasure";
	global.__objectNames[375] = "obj_pizzaboxunopen";
	global.__objectNames[376] = "obj_collect";
	global.__objectNames[377] = "obj_pizzakinsausage";
	global.__objectNames[378] = "obj_pizzakinshroom";
	global.__objectNames[379] = "obj_pizzakincheese";
	global.__objectNames[380] = "obj_pizzakintomato";
	global.__objectNames[381] = "obj_pizzakinpineapple";
	global.__objectNames[382] = "obj_noisebomb";
	global.__objectNames[383] = "obj_bigcollect";
	global.__objectNames[384] = "obj_giantcollect";
	global.__objectNames[385] = "obj_clockcollectibles";
	global.__objectNames[386] = "obj_key";
	global.__objectNames[387] = "obj_clockcollectibles2";
	global.__objectNames[388] = "obj_pizzaslice";
	global.__objectNames[389] = "obj_pizzacoin";
	global.__objectNames[390] = "obj_phonebooth";
	global.__objectNames[391] = "obj_hungrypillar";
	global.__objectNames[392] = "obj_exitgate";
	global.__objectNames[393] = "obj_snicklevelend";
	global.__objectNames[394] = "obj_portalentrance";
	global.__objectNames[395] = "obj_portalend";
	global.__objectNames[396] = "obj_costumerdoor";
	global.__objectNames[397] = "obj_costumer";
	global.__objectNames[398] = "obj_costumerpizza";
	global.__objectNames[399] = "obj_cheeseball";
	global.__objectNames[400] = "obj_wetfloor";
	global.__objectNames[401] = "obj_noisebombspawner";
	global.__objectNames[402] = "obj_slipnslide";
	global.__objectNames[403] = "obj_superspring";
	global.__objectNames[404] = "obj_sidesuperspring";
	global.__objectNames[405] = "obj_beartrap";
	global.__objectNames[406] = "obj_balloon";
	global.__objectNames[407] = "obj_bowlingball";
	global.__objectNames[408] = "obj_skateboard";
	global.__objectNames[409] = "obj_pizzacutterthwomp2";
	global.__objectNames[410] = "obj_pizzacutterthwomp1";
	global.__objectNames[411] = "obj_throwableparent";
	global.__objectNames[412] = "obj_keydoor";
	global.__objectNames[413] = "obj_breakabledoor";
	global.__objectNames[414] = "obj_goldendoor";
	global.__objectNames[415] = "obj_doorblocked";
	global.__objectNames[416] = "obj_startgate";
	global.__objectNames[417] = "obj_door";
	global.__objectNames[418] = "obj_boxofpizza";
	global.__objectNames[419] = "obj_hallway";
	global.__objectNames[420] = "obj_pitfall";
	global.__objectNames[421] = "obj_door2";
	global.__objectNames[422] = "obj_doorA";
	global.__objectNames[423] = "obj_doorB";
	global.__objectNames[424] = "obj_doorC";
	global.__objectNames[425] = "obj_doorD";
	global.__objectNames[426] = "obj_doorE";
	global.__objectNames[427] = "obj_pizzacutter1";
	global.__objectNames[428] = "obj_swordstone";
	global.__objectNames[429] = "obj_pizzacutter2";
	global.__objectNames[430] = "obj_thunder";
	global.__objectNames[431] = "obj_destructibleplatform";
	global.__objectNames[432] = "obj_boilingsauce";
	global.__objectNames[433] = "obj_risingboilingsauce";
	global.__objectNames[434] = "obj_noisetrap_rock";
	global.__objectNames[435] = "obj_dashpad";
	global.__objectNames[436] = "obj_tntblock";
	global.__objectNames[437] = "obj_rockblock";
	global.__objectNames[438] = "obj_noiserock";
	global.__objectNames[439] = "obj_boulder";
	global.__objectNames[440] = "obj_noisedynamite";
	global.__objectNames[441] = "obj_freemilk";
	global.__objectNames[442] = "obj_motocycle";
	global.__objectNames[443] = "obj_haystack";
	global.__objectNames[444] = "obj_noisehotair";
	global.__objectNames[445] = "obj_noisematch";
	global.__objectNames[446] = "obj_grabbiehand";
	global.__objectNames[447] = "obj_boxcrusher";
	global.__objectNames[448] = "obj_cheeseblob";
	global.__objectNames[449] = "obj_cheesemaker";
	global.__objectNames[450] = "obj_railv";
	global.__objectNames[451] = "obj_railh2";
	global.__objectNames[452] = "obj_railh";
	global.__objectNames[453] = "obj_hook";
	global.__objectNames[454] = "obj_hookup";
	global.__objectNames[455] = "obj_hookleft";
	global.__objectNames[456] = "obj_barrelspawner";
	global.__objectNames[457] = "obj_transformbarrelspawner";
	global.__objectNames[458] = "obj_transformbarrel";
	global.__objectNames[459] = "obj_barrel";
	global.__objectNames[460] = "obj_barrelfloat";
	global.__objectNames[461] = "obj_tomatoblock";
	global.__objectNames[462] = "obj_washingmachinemount";
	global.__objectNames[463] = "obj_baddiegibs";
	global.__objectNames[464] = "obj_washingmachine";
	global.__objectNames[465] = "obj_wooddebris";
	global.__objectNames[466] = "obj_slapstar";
	global.__objectNames[467] = "obj_pizzadebris";
	global.__objectNames[468] = "obj_debris";
	global.__objectNames[469] = "obj_dripspawner";
	global.__objectNames[470] = "object189";
	global.__objectNames[471] = "obj_knightdebris";
	global.__objectNames[472] = "obj_boxxeddebris";
	global.__objectNames[473] = "obj_glassdebris";
	global.__objectNames[474] = "obj_vomit";
	global.__objectNames[475] = "obj_slimedebris";
	global.__objectNames[476] = "obj_metaldebris";
	global.__objectNames[477] = "obj_drip";
	global.__objectNames[478] = "obj_skateboarddebris1";
	global.__objectNames[479] = "obj_lock";
	global.__objectNames[480] = "obj_pizzaloss";
	global.__objectNames[481] = "obj_skateboarddebris2";
	global.__objectNames[482] = "obj_parentparticle";
	global.__objectNames[483] = "obj_tntblockdebris";
	global.__objectNames[484] = "obj_vsscreen";
	global.__objectNames[485] = "obj_goalsign";
	global.__objectNames[486] = "obj_siren";
	global.__objectNames[487] = "obj_exitdoorsign";
	global.__objectNames[488] = "obj_plusseconds";
	global.__objectNames[489] = "obj_ranksign";
	global.__objectNames[490] = "obj_donesign";
	global.__objectNames[491] = "obj_Hranksign";
	global.__objectNames[492] = "obj_press";
	global.__objectNames[493] = "obj_uparrow";
	global.__objectNames[494] = "obj_creditimages";
	global.__objectNames[495] = "obj_leveltitles";
	global.__objectNames[496] = "obj_easy";
	global.__objectNames[497] = "obj_100";
	global.__objectNames[498] = "obj_80";
	global.__objectNames[499] = "obj_40";
	global.__objectNames[500] = "obj_20";
	global.__objectNames[501] = "obj_smallnumber";
	global.__objectNames[502] = "obj_cowboyhat";
	global.__objectNames[503] = "obj_treasureshadow";
	global.__objectNames[504] = "obj_Opeppino";
	global.__objectNames[505] = "obj_itspizzatime";
	global.__objectNames[506] = "obj_grabmarker";
	global.__objectNames[507] = "obj_ballgoal";
	global.__objectNames[508] = "obj_noisesatellite";
	global.__objectNames[509] = "obj_glassblock";
	global.__objectNames[510] = "obj_tutorialtrap";
	global.__objectNames[511] = "obj_crashingplane";
	global.__objectNames[512] = "obj_crashplaneblock";
	global.__objectNames[513] = "obj_pizzaballblock";
	global.__objectNames[514] = "obj_lamp";
	global.__objectNames[515] = "obj_lightlamp";
	global.__objectNames[516] = "obj_daynight";
	global.__objectNames[517] = "obj_speedlines";
	global.__objectNames[518] = "obj_pizzaportalfade";
	global.__objectNames[519] = "obj_angrycloud";
	global.__objectNames[520] = "obj_sweat";
	global.__objectNames[521] = "obj_balloonpop";
	global.__objectNames[522] = "obj_bulletimpact";
	global.__objectNames[523] = "obj_bulletdisappear";
	global.__objectNames[524] = "obj_chargeeffect";
	global.__objectNames[525] = "obj_pogoeffect";
	global.__objectNames[526] = "obj_chainsaweffect";
	global.__objectNames[527] = "obj_explosioneffect";
	global.__objectNames[528] = "obj_pistoleffect";
	global.__objectNames[529] = "obj_shotgunjumpeffect";
	global.__objectNames[530] = "obj_superslameffect";
	global.__objectNames[531] = "obj_spikehurteffect";
	global.__objectNames[532] = "obj_stompeffect";
	global.__objectNames[533] = "obj_jumpdust";
	global.__objectNames[534] = "obj_superdashcloud";
	global.__objectNames[535] = "obj_highjumpcloud1";
	global.__objectNames[536] = "obj_highjumpcloud2";
	global.__objectNames[537] = "obj_grindeffect";
	global.__objectNames[538] = "obj_punchdust";
	global.__objectNames[539] = "obj_fadeout";
	global.__objectNames[540] = "obj_pausefadeout";
	global.__objectNames[541] = "obj_endlevelfade";
	global.__objectNames[542] = "obj_bossdefeatflash";
	global.__objectNames[543] = "obj_bangeffect";
	global.__objectNames[544] = "obj_blackbars";
	global.__objectNames[545] = "obj_bumpeffect";
	global.__objectNames[546] = "obj_keyeffect";
	global.__objectNames[547] = "obj_doortransition";
	global.__objectNames[548] = "obj_doortransitionend";
	global.__objectNames[549] = "obj_doortransition2";
	global.__objectNames[550] = "obj_slidecloud";
	global.__objectNames[551] = "obj_landcloud";
	global.__objectNames[552] = "obj_dashcloud";
	global.__objectNames[553] = "obj_dashcloud2";
	global.__objectNames[554] = "obj_cloudeffect";
	global.__objectNames[555] = "obj_machalleffect";
	global.__objectNames[556] = "obj_mach3effect";
	global.__objectNames[557] = "obj_crazyruneffect";
	global.__objectNames[558] = "obj_crazyrunothereffect";
	global.__objectNames[559] = "obj_taunteffect";
	global.__objectNames[560] = "obj_tauntafterimage";
	global.__objectNames[561] = "obj_tauntaftereffectspawner";
	global.__objectNames[562] = "obj_snick";
	global.__objectNames[563] = "obj_snickexe";
	global.__objectNames[564] = "obj_SAGE2019achievementmarker";
	global.__objectNames[565] = "obj_snickchallengedoor";
	global.__objectNames[566] = "obj_cowboytask";
	global.__objectNames[567] = "obj_cowboyhatpickup";
	global.__objectNames[568] = "obj_characterchangecube";


	var len = array_length_1d(global.__objectDepths)
	global.__objectID2Depth = []
	for (var i = 0; i < len; i++)
	{
	    var objID = asset_get_index(global.__objectNames[i])
	    if (objID >= 0)
	        global.__objectID2Depth[objID] = global.__objectDepths[i]
	}





}
