var _cam_x = camera_get_view_x(view_camera[0])
var _cam_y = camera_get_view_y(view_camera[0])
layer_x("Backgrounds_1", (_cam_x * 0.25))
layer_y("Backgrounds_1", (_cam_y * 0.25))
layer_x("Backgrounds_2", (_cam_x * 0.15))
layer_y("Backgrounds_2", (_cam_y * 0.15))
layer_x("Backgrounds_3", (_cam_x * 0.05))
layer_y("Backgrounds_3", (_cam_y * 0.05))
layer_x("Backgrounds_statue", (_cam_x * 0.10))
layer_x("Backgrounds_Ground1", (_cam_x * 0.25))
layer_x("Backgrounds_Ground2", (_cam_x * 0.25))
layer_x("Backgrounds_H1", (_cam_x * 0.25))
layer_y("Backgrounds_H1", _cam_y)
layer_x("Backgrounds_sky", (_cam_x * 0.85))
layer_y("Backgrounds_sky", (_cam_y * 0.85))
layer_x("Backgrounds_sky2", _cam_x)
layer_y("Backgrounds_sky2", _cam_y)
layer_x("Backgrounds_still1", (_cam_x - clamp((_cam_x * (0.15 * (960 / room_width))), 0, (sprite_get_width(layer_background_get_sprite(layer_background_get_id(layer_get_id("Backgrounds_still1")))) - 960))))
layer_y("Backgrounds_still1", (_cam_y - clamp((_cam_y * (0.15 * (540 / room_height))), 0, (sprite_get_height(layer_background_get_sprite(layer_background_get_id(layer_get_id("Backgrounds_still1")))) - 540))))
layer_x("Backgrounds_stillH1", (_cam_x * 0.25))
layer_y("Backgrounds_stillH1", (_cam_y - clamp((_cam_y * (0.15 * (540 / room_height))), 0, (sprite_get_height(layer_background_get_sprite(layer_background_get_id(layer_get_id("Backgrounds_stillH1")))) - 540))))
