with (obj_player)
{
    grav = 0.5
    hsp = 0
    vsp = 0
    xscale = 1
    yscale = 1
    movespeed = 0
    movespeedmax = 5
    jumpstop = 0
    start_running = 1
    state = 100
    turn = 0
    jumpAnim = 1
    dashAnim = 1
    landAnim = 0
    machslideAnim = 1
    moveAnim = 1
    stopAnim = 1
    crouchslideAnim = 1
    crouchAnim = 1
    machhitAnim = 0
    stompAnim = 0
    inv_frames = 0
    turning = 0
    hurtbounce = 0
    hurted = 0
    mach2 = 0
    input_buffer_jump = 8
    player_x = x
    player_y = y
    targetRoom = 0
    flash = 0
    global.key_inv = 0
    global.shroomfollow = 0
    global.cheesefollow = 0
    global.tomatofollow = 0
    global.sausagefollow = 0
    global.pineapplefollow = 0
    global.keyget = 0
    global.collect = 0
    global.ammo = 0
    global.panic = 0
	global.combo = 0
    //combo = 0
    in_water = 0
    key_particles = 0
    barrel = 0
    bounce = 0
    a = 0
    idle = 0
    attacking = 0
    slamming = 0
    superslam = 0
    machpunchAnim = 0
    punch = 0
    machfreefall = 0
    shoot = 1
    instakillmove = 0
    windingAnim = 0
    facestompAnim = 0
    ladderbuffer = 0
    toomuchalarm1 = 0
    dashdust = 0
    throwforce = 0
    hurtsound = 0
    bombpephitwall = 0
    idleanim = 0
    momemtum = 0
	bubble = 0
	depth = -6
	combotimer = 0
	bossfallout = 0
	ini_open("saveData.ini")
	global.setting_machsound = ini_read_string("Settings", "machsound", 1)
	global.setting_zoomorshake = ini_read_string("Settings", "zoomorshake", 1)
	global.setting_newdoors = ini_read_string("Settings", "newdoors", 1)
	if global.setting_machsound = 1
		global.machsound = 1
	else if global.setting_machsound = 2
		global.machsound = 2
	else if global.setting_machsound = 3
		global.machsound = 3
	if global.setting_zoomorshake = 1
		global.zoomorshake = 1
	else if global.setting_zoomorshake = 2
		global.zoomorshake = 2
	else if global.setting_zoomorshake = 3
		global.zoomorshake = 3
	if global.setting_newdoors = 1
		global.newdoors = 1
	else if global.setting_newdoors = 2
		global.newdoors = 2
	ini_close()
	global.gotshotgun = 0
	global.gotchainsaw = 0
	global.ammo = 10
	global.sawpower = 100
	targetDoor = "A"
	hallway = 0
	box = 0
	hallwaydirection = 0
	lastroom_x = 0
	lastroom_y = 0
	lastroom = 0
	pitfall = 0
	global.rank = 0
}


